[package]
name = "shachecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.8"
data-encoding = "2.6.0"
env_logger = "0.11.3"
log = "0.4.21"

[profile.release]
lto = "thin"
